### PR TITLE
built footer, added bootstrap, jquery and popper.js

### PR DESCRIPTION
**Pull request by phiiileo**

### CODE REVIEW

**Comment by phiiileo** [comment]
https://phiiileo.github.io/lit-page/site_footer.html

**Comment by phiiileo** [comment]
https://phiiileo.github.io/lit-page/site_footer.html

**Comment by lixir-org** [comment]
I'll merge this PR but I'm very sure it's not all the libraries included that would be used so hope you don't mind me removing some of them that are not used later when other pages are complete?

**Comment by phiiileo** [comment]
Yes definitely, if we will be using bootstrap those libraries are needed, it should have been cdn links but some might want to work offline. But anyways do what you think is the best

**Pull request merged**
